# Generated by Selenium IDE
from email.headerregistry import Group
from cv2 import grabCut
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class crawlMangaPageImage():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def crawlImage(self):
    self.driver.get("http://www.nettruyenmoi.com/truyen-tranh/19-days/chap-454/675633")
    self.driver.set_window_size(682, 518)
    # with open('page.html', 'w',encoding='utf-8') as f:
    #   f.write(self.driver.page_source)
    ActionChains(self.driver).key_down(Keys.COMMAND).send_keys("s").key_up(Keys.COMMAND).perform()
    time.sleep(5)
    # Tìm cái div chứa tất cả các hình
    # groupImageDiv = self.driver.find_element(By.CLASS_NAME,'reading-detail').find_elements(By.CLASS_NAME,'li')
    # groupHrefDiv = self.driver.find_element(By.TAG_NAME,'li')
    # a = self.driver.find_element_by_id('a').get_attribute('b').tex
    # List các href
    #  hrefList = []

    # Duyệt cái div đó lấy ra từng page
    # for childElement in groupHrefDiv:
    #     print("Hello")
    #     print(childElement.get_attribute('data-boxtype'))
        


# Gọi class đó
sele = crawlMangaPageImage()
sele.setup_method()
sele.crawlImage()
sele.teardown_method()

