   chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-1.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-1/526047
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-79.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-79/831305
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-78.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-78/827183
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-77.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-77/820081
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-76.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-76/818007
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-75.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-75/815602
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-74.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-74/813264
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-73.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-73/805351
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-72.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-72/799103
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-71.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-71/792680
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-70.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-70/792679
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-69.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-69/781251
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-68.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-68/779252
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-67.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-67/774784
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-66.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-66/770044
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-65.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-65/766657
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-64.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-64/766655
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-63.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-63/766654
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-62.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-62/762736
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-61.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-61/760218
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-60.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-60/757303
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-59.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-59/752515
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-58.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-58/752514
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-57.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-57/752513
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-56.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-56/752512
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-55.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-55/752511
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-30.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-30/644601
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-29.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-29/640935
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-28.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-28/634885
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-27.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-27/632457
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-26.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-26/626970
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-25.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-25/622073
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-24.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-24/619022
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-23.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-23/612645
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-22.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-22/610056
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-21.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-21/598427
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-20.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-20/591512
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-19.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-19/584356
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-18.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-18/580441
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-17.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-17/573470
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-16.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-16/570660
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-15.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-15/565569
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-14.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-14/563468
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-13.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-13/561026
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-12.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-12/558934
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-11.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-11/556492
                                                                                                                                                                                                                                                                Start-Sleep 6
 chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-10.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-10/556491
                                                                                                                                                                                                                                                                Start-Sleep 6
   chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-9.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-9/551043
                                                                                                                                                                                                                                                                Start-Sleep 6
   chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-8.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-8/545939
                                                                                                                                                                                                                                                                Start-Sleep 6
   chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-7.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-7/544150
                                                                                                                                                                                                                                                                Start-Sleep 6
   chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-6.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-6/542053
                                                                                                                                                                                                                                                                Start-Sleep 6
   chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-5.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-5/540006
                                                                                                                                                                                                                                                                Start-Sleep 6
   chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-4.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-4/535672
                                                                                                                                                                                                                                                                Start-Sleep 6
   chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-3.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-3/531133
                                                                                                                                                                                                                                                                Start-Sleep 6
   chrome --enable-logging --headless --disable-gpu --print-to-pdf=d:\Code\pythonProjectGroup\WebScrappingBeginner\nettruyen_downloader\FANTASY BISHOUJO JUNIKU OJISAN TO\chap-2.pdf http://www.nettruyenmoi.com/truyen-tranh/fantasy-bishoujo-juniku-ojisan-to/chap-2/527143
                                                                                                                                                                                                                                                                Start-Sleep 6